version: '3'

tasks:
  format:
    desc: "layout.vil を整形してインデントを挿入"
    cmds:
      - 'jq . layout.vil > layout.vil.tmp && mv layout.vil.tmp layout.vil'

  minify:
    desc: "layout.vil を1行に圧縮"
    cmds:
      - 'jq -c . layout.vil > layout.vil.tmp && mv layout.vil.tmp layout.vil'

  hub:
    desc: "cornixhubを開く"
    cmds:
      - 'open https://cornixhub.com/keymap'

  diff:
    desc: "直近のコミットのdiffをgithubで確認する"
    cmds:
      - 'gh browse $(git rev-parse HEAD)'
